### PR TITLE
Created ER diagram for project

### PR DESCRIPTION
**Pull request by AymanJabr**
In this pull request we created a design of the ER diagram of the different models that might be used in this project. The design can be found under `docs/Social media website ER.png`

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [x] The user table should have an image_link column. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
- [x] You are currently missing a likes table. Add the Likes table with the appropriate associations.
- [x] Assign the Primary and Foreign Keys (PK & FK) to your tables. Each table should include the ID column that will hold your PKs. They are currently missing.
- [x] Relationship between the User and Friendship table should be as follows
```
1. One Friendship  is sent by only One User.
2. One User can send many Friendships.
3. One Friendship is received by only One User.
4. One User can receive many Friendships.
```

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Ping me on slack for a chit-chat 🆘  Roy Mukuye Or mention me in this PR

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED 🔴 ♻️ 

Hello team @AymanJab 👋🏾 👋🏾 , congratulations on making it this far on this milestone. I like that you have tried to implement the previous TSE comments, keep it up. Your ERD is almost complete but a few changes need to be made first.
Kindly implement the following relationships:- 

- [x] One User can create many Posts.
- [x]  One Post is created by only One User.


That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**Thanks for implementing the changes requested earlier on**. However, there are a few more issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [x] As mentioned earlier, add the Primary/Foreign Key columns to all your tables. The PK will only contain the table's ID and all the linked tables will have the FK assigned.
- [x] In the Users table, you are having the `user_id`. The appropriate naming convention should be `ID` and it should be assigned as the PK. The same applies to the Post table. You should only use `user_id` or `post_id` etc if it is a FK in another table.

Screenshot_2021-04-05_15-12-19


> Hope my explanation is clear to you.

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Ping me on slack for a chit-chat 🆘  Roy Mukuye Or mention me in this PR

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations on completing this milestone. 
I see you have successfully implemented all the changes requested by the previous TSE. 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
