### PR TITLE
Created the Friendship relationship

### PR DESCRIPTION
**Pull request by AymanJabr**
This relationship relates a User to the friends he has, and the ones that he has sent friend requests to, or received friend requests from, but are still not confirmed.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @AymanJabr and @FrederickMih   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this milestone. However your code review request is marked as invalid due to the following reasons:
The submitted pull request has failing linters errors, kindly fix all of them and then submit another review request

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello Team :)
Great work and effort you put into this milestone.
Linter is well-configured ✔
Models' associations are correct ✔
However, there are still a few more changes to make in order to get the approval 🙏

- [x] Please make sure that a user can send friendship invites to other users, and those other users have to accept the request to initiate a friendship or to reject to cancel it.
send_invitation
pending_request
accept_reject_friendship

- [ ] Kindly add the button "Friendship Invite" at the right bottom of each user's name who's not already friend with the current user (logged_in user), and that button has to be in both "All Users" and the user's profile pages. Also, on the other side, the user of received the invitation should see two other buttons "Accept" and "Reject" at the right bottom of the user's name who sent the invitation.
user_can_see_invite_buttton

- [x] Please set up the proper logic for the timeline posts. It should only available for a user to see his friends' posts (Friends who have already accepted the invitation)
friends_timeline

- [x] I'm afraid you forgot about the unit and integration tests. Kindly write test cases for the models and features of the app. Currently, there are 0 examples!
tests

- [x] Please keep in mind in the future that professionally, you should write more descriptive commit messages about every change you make in the app during the Dev Mode.

<hr>

Kindly after you do the required changes, ask for another CRR 👍 
Please feel free to contact me on Slack with the name "Mahmoud Bakr" if you had any questions!
Good luck and happy coding. 👨‍💻💻

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔✔**

Hello guys,
This is a great implementation of the required changes👍👍
You can merge and move on

Happy coding💻💻💻💻

**Comment by AymanJabr** [comment]
Could you please explain to us in a bit more detail what the 3rd milestone requires? We are not too sure from the material that was provided.

**Pull request merged**
